import {FeedbackComponent} from "@/types/feedbackComponent";
import {Exercise} from "@/types/exercise";
import {TaskType} from "@/types/taskType";
import {Error} from "@/types/error";

export interface Feedback {
    id: number;                    // Auto-generated by database
    feedback_code: string;          // Unique code, e.g. "BO.1"
    description: string;           // Description text

    components: FeedbackComponent[];  // Associated feedback components

    errorPointed: boolean;         // Whether feedback points out errors
    pointedErrors?: Error[];       // List of pointed errors (if any)

    associatedExercises?: Exercise[]; // Linked exercises
    associatedTaskTypes?: TaskType[]; // Linked task types
}